import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGroup87Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedEmpalgentongmangdarmakulinercirebonlegendaris32Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedOpen1000Closes1800Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedJlTuparevNo43BSutawinangunKecKedawungKabCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedAEMPALASAMibusopia1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedOpen0700Closes1930Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedOpen0900Closes2100Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGroup86Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedEmpalAsemIburunipa1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGgPurnamaSamadikunKecKejaksanKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedOpen0700Closes2100Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedH4Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedJlPDiponegoroNo23KesendenKecKejaksanKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGroup85Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedLine3Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGroup83Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGroup84Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedLine2Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedGesikKecTengahTaniKabupatenCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget13/generated/GeneratedLine6Widget4.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 36.0,
                child: GeneratedGroup87Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget5(),
              ),
              Positioned(
                left: 20.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 22.0,
                child: GeneratedGroup86Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget5(),
              ),
              Positioned(
                left: 0.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget4(),
              ),
              Positioned(
                left: 14.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 140.0,
                child: GeneratedH4Widget1(),
              ),
              Positioned(
                left: 20.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0700Closes2100Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 310.0,
                height: 16.0,
                child:
                    GeneratedJlPDiponegoroNo23KesendenKecKejaksanKotaCirebonWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 799.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0700Closes1930Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 16.0,
                child: GeneratedGesikKecTengahTaniKabupatenCirebonWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 16.0,
                child:
                    GeneratedJlTuparevNo43BSutawinangunKecKedawungKabCirebonWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0900Closes2100Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 266.0,
                height: 16.0,
                child:
                    GeneratedGgPurnamaSamadikunKecKejaksanKotaCirebonWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen1000Closes1800Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 302.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 133.0,
                child:
                    GeneratedEmpalgentongmangdarmakulinercirebonlegendaris32Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 115.0,
                child: GeneratedAEMPALASAMibusopia1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 125.0,
                child: GeneratedEmpalAsemIburunipa1Widget(),
              )
            ]),
      ),
    ));
  }
}
