import 'package:flutter/material.dart';

/* Rectangle 36147945_409398012896798_2485115154602131456_n-300x300 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated36147945_409398012896798_2485115154602131456_n300x3001W1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 332.37408447265625,
      height: 200.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(15.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Image.asset(
          "assets/images/56d9e147953ba590384175bf14994074e1719b74.png",
          color: null,
          fit: BoxFit.cover,
          width: 332.37408447265625,
          height: 200.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
