import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro143widget/generated/GeneratedWisataKulinerkhasCirebonWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro143widget/generated/GeneratedKabargembirabuatkamuyanginginmenikmatiwisatakulinerdiCi1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro143widget/generated/GeneratedKulinerTopCirebon1Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro143widget/generated/GeneratedFrame2Widget1.dart';

/* Frame MacBook Pro 14" - 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro143Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 982.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                        gradient: LinearGradient(
                          begin: Alignment(0.0, -1.0),
                          end: Alignment(0.0, 0.9999999999999998),
                          stops: [0.0, 0.9998999834060669, 1.0],
                          colors: [
                            Color.fromARGB(255, 191, 211, 228),
                            Color.fromARGB(238, 191, 211, 228),
                            Color.fromARGB(0, 0, 132, 255)
                          ],
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            Positioned(
                              left: 89.0,
                              top: 523.0,
                              right: null,
                              bottom: null,
                              width: 1336.0,
                              height: 444.0,
                              child:
                                  GeneratedKabargembirabuatkamuyanginginmenikmatiwisatakulinerdiCi1(),
                            ),
                            Positioned(
                              left: 431.0,
                              top: 98.0,
                              right: 433.0,
                              bottom: null,
                              width: null,
                              height: 152.0,
                              child: GeneratedWisataKulinerkhasCirebonWidget1(),
                            ),
                            Positioned(
                              left: 504.0,
                              top: 324.0,
                              right: null,
                              bottom: null,
                              width: 505.0,
                              height: 333.0,
                              child: GeneratedKulinerTopCirebon1Widget3(),
                            ),
                            Positioned(
                              left: null,
                              top: null,
                              right: 79.0,
                              bottom: 65.0,
                              width: 272.0,
                              height: 64.0,
                              child: GeneratedFrame2Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
