import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall4widget/generated/GeneratedKabargembirabuatkamuyanginginmenikmatiwisatakulinerdiCi.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall4widget/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall4widget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall4widget/generated/GeneratedKulinerTopCirebon1Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall4widget/generated/GeneratedWisataKulinerkhasCirebonWidget.dart';

/* Frame Android Small - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 68.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 32.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: -10.0,
                top: 184.0,
                right: null,
                bottom: null,
                width: 396.0,
                height: 86.0,
                child:
                    GeneratedKabargembirabuatkamuyanginginmenikmatiwisatakulinerdiCi(),
              ),
              Positioned(
                left: 55.0,
                top: 102.0,
                right: 53.0,
                bottom: null,
                width: null,
                height: 58.0,
                child: GeneratedWisataKulinerkhasCirebonWidget(),
              ),
              Positioned(
                left: 83.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 159.0,
                child: GeneratedKulinerTopCirebon1Widget1(),
              ),
              Positioned(
                left: null,
                top: null,
                right: 16.0,
                bottom: 56.0,
                width: 142.0,
                height: 40.0,
                child: GeneratedFrame2Widget(),
              )
            ]),
      ),
    ));
  }
}
