import 'package:flutter/material.dart';

/* Rectangle unnamed-4 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUnnamed41Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 234.0,
      height: 123.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(15.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Image.asset(
          "assets/images/c9df3541a26a0a197253cdc7c6ac6a0c0f792cde.png",
          color: null,
          fit: BoxFit.cover,
          width: 234.0,
          height: 123.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
