import 'package:flutter/material.dart';

/* Text Jl. DR. Cipto Mangunkusumo, Pekiringan, Kec. Kesambi, Kota Cirebon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJlDRCiptoMangunkusumoPekiringanKecKesambiKotaCirebonWid
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Jl. DR. Cipto Mangunkusumo, Pekiringan, Kec. Kesambi, Kota Cirebon''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
