import 'package:flutter/material.dart';

/* Text Desa Setu Wetan Blok Kedung Bawang RT.13/RW.05,Setu Wetan,Kec. Weru
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDesaSetuWetanBlokKedungBawangRT13RW05SetuWetanKecWeruWi
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Desa Setu Wetan Blok Kedung Bawang RT.13/RW.05,Setu Wetan,Kec. Weru''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
