import 'package:flutter/material.dart';

/* Text Karangsari, Kec. Weru, Kabupaten Cirebon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKarangsariKecWeruKabupatenCirebonWidget1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Karangsari, Kec. Weru, Kabupaten Cirebon''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 0.95,
        fontSize: 20.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
