import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedIcbaselineplusWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedSampul166216636476041Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedFrame79Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedGroup90Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedGroup91Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedSelengkapnyaWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedRectangle58Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedSelengkapnyaWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedNasijamblangberupanasiyangdibungkusdengandaunjatidandil.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedEips7xuyao2hvd779945a94fa2a8b20445c2e7e4ba0a19_600x4001.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedGroup80Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedGroup82Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedKebiasaandariparapenjualnyayangmenaruhairgulamerahdalam.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedGroup81Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedSelengkapnyaWidget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedRectangle11Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedEmpalGentongmerupakanmakananyangberasaldariTimurTengahy.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedSelengkapnyaWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget/generated/GeneratedGroup89Widget.dart';

/* Frame Rekomendasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRekomendasiWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 110.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 176.80482482910156,
                height: 17.473678588867188,
                child: GeneratedGroup80Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 539.0,
                right: null,
                bottom: null,
                width: 176.80482482910156,
                height: 17.473678588867188,
                child: GeneratedGroup82Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 110.0,
                child: GeneratedRectangle9Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 181.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 117.0,
                child:
                    GeneratedEmpalGentongmerupakanmakananyangberasaldariTimurTengahy(),
              ),
              Positioned(
                left: 251.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle10Widget(),
              ),
              Positioned(
                left: 274.0,
                top: 273.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 17.792469024658203,
                child: GeneratedGroup81Widget(),
              ),
              Positioned(
                left: 112.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 17.792469024658203,
                child: GeneratedGroup91Widget(),
              ),
              Positioned(
                left: 111.0,
                top: 318.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 43.0,
                child:
                    GeneratedNasijamblangberupanasiyangdibungkusdengandaunjatidandil(),
              ),
              Positioned(
                left: 111.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 76.0,
                child:
                    GeneratedKebiasaandariparapenjualnyayangmenaruhairgulamerahdalam(),
              ),
              Positioned(
                left: 113.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 76.0,
                child:
                    GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones(),
              ),
              Positioned(
                left: 251.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle11Widget(),
              ),
              Positioned(
                left: 251.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle13Widget(),
              ),
              Positioned(
                left: 251.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle12Widget(),
              ),
              Positioned(
                left: 274.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget1(),
              ),
              Positioned(
                left: 274.0,
                top: 652.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget2(),
              ),
              Positioned(
                left: 12.0,
                top: 297.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 92.0,
                child:
                    GeneratedEips7xuyao2hvd779945a94fa2a8b20445c2e7e4ba0a19_600x4001(),
              ),
              Positioned(
                left: 13.0,
                top: 418.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 97.0,
                child: GeneratedSampul166216636476041Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 96.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 273.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget3(),
              ),
              Positioned(
                left: 321.0,
                top: 705.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup89Widget(),
              ),
              Positioned(
                left: 327.0,
                top: 710.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselineplusWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 78.0,
                child: GeneratedRectangle58Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 94.0,
                child: GeneratedFrame79Widget(),
              ),
              Positioned(
                left: 316.0,
                top: 65.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 36.0,
                child: GeneratedGroup90Widget(),
              )
            ]),
      ),
    ));
  }
}
