import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedJlKesambiKesambiKecKesambiKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedDocangibukapsahcirebon_medium1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGroup87Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedJlSiliwangiNo77KesendenKecKejaksanKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedLine6Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedLine2Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedJlTentaraPelajarPekiringanKecKesambiKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGroup77Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedDocangpakkumis1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGroup86Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGroup84Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedOpen0600Closes1500Open1600Closes0200Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGgJakaLestariAdidharmaKecGunungjatiKabupatenCirebonWidg.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGroup83Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedGroup85Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedOpen0400Closes1100Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedOpen0600Closes1100Open1700Closes2100Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedLine3Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedDocangwiwi1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedDocangumbul1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget14/generated/GeneratedOpen1500Closes2000Widget.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget6(),
              ),
              Positioned(
                left: 161.0,
                top: 28.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 27.0,
                child: GeneratedGroup87Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget6(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 22.0,
                child: GeneratedGroup86Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget5(),
              ),
              Positioned(
                left: 21.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen1500Closes2000Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 16.0,
                child:
                    GeneratedGgJakaLestariAdidharmaKecGunungjatiKabupatenCirebonWidg(),
              ),
              Positioned(
                left: 21.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 261.0,
                height: 16.0,
                child: GeneratedOpen0600Closes1500Open1600Closes0200Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 16.0,
                child: GeneratedJlKesambiKesambiKecKesambiKotaCirebonWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0400Closes1100Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 16.0,
                child:
                    GeneratedJlSiliwangiNo77KesendenKecKejaksanKotaCirebonWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 259.0,
                right: null,
                bottom: null,
                width: 268.0,
                height: 16.0,
                child: GeneratedOpen0600Closes1100Open1700Closes2100Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 16.0,
                child:
                    GeneratedJlTentaraPelajarPekiringanKecKesambiKotaCirebonWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 125.0,
                child: GeneratedDocangibukapsahcirebon_medium1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 116.0,
                child: GeneratedDocangwiwi1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 672.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 105.0,
                child: GeneratedDocangumbul1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 105.0,
                right: null,
                bottom: null,
                width: 244.0,
                height: 129.0,
                child: GeneratedDocangpakkumis1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 23.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup77Widget4(),
              )
            ]),
      ),
    ));
  }
}
