import 'package:flutter/material.dart';

/* Rectangle 20220303_140805 1
    Autogenerated by FlutLab FTF Generator
  */
class Generated20220303_1408051Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 233.0,
      height: 141.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(15.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Image.asset(
          "assets/images/d2bd8f14e1f92df065802a508848f5ccc0d2f7df.png",
          color: null,
          fit: BoxFit.cover,
          width: 233.0,
          height: 141.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
