import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedKerupukmelaratadalahsalahsatumakanankhasCirebondansekit.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedGroup80Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedRectangle58Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedMakanantradisionalyangberasaldariCirebondansekitarnyaya.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedSelengkapnyaWidget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedImage6Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedFrame79Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedGroup90Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedRasaempalaseminisegarkarenamenggunakanbelimbingwuluhdan.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedRectangle11Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedMerupakanperpaduanbahanutamanasidenganberbagaisayuranda.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedSelengkapnyaWidget7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedSelengkapnyaWidget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedIcbaselineplusWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedGroup81Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedGroup91Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedGroup82Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedrekomendasiwidget2/generated/GeneratedSelengkapnyaWidget5.dart';

/* Frame Rekomendasi
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRekomendasiWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 110.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 176.80482482910156,
                height: 17.473678588867188,
                child: GeneratedGroup80Widget1(),
              ),
              Positioned(
                left: 111.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 176.80482482910156,
                height: 17.473678588867188,
                child: GeneratedGroup82Widget1(),
              ),
              Positioned(
                left: 112.0,
                top: 554.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 58.0,
                child:
                    GeneratedMerupakanperpaduanbahanutamanasidenganberbagaisayuranda(),
              ),
              Positioned(
                left: 111.0,
                top: 179.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 117.0,
                child:
                    GeneratedKerupukmelaratadalahsalahsatumakanankhasCirebondansekit(),
              ),
              Positioned(
                left: 251.0,
                top: 261.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle10Widget1(),
              ),
              Positioned(
                left: 274.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget4(),
              ),
              Positioned(
                left: 111.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 178.80482482910156,
                height: 138.4736785888672,
                child: GeneratedGroup81Widget1(),
              ),
              Positioned(
                left: 111.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 43.0,
                child:
                    GeneratedMakanantradisionalyangberasaldariCirebondansekitarnyaya(),
              ),
              Positioned(
                left: 114.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 76.0,
                child:
                    GeneratedRasaempalaseminisegarkarenamenggunakanbelimbingwuluhdan(),
              ),
              Positioned(
                left: 251.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle11Widget1(),
              ),
              Positioned(
                left: 251.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle13Widget1(),
              ),
              Positioned(
                left: 251.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 113.0,
                height: 21.0,
                child: GeneratedRectangle12Widget1(),
              ),
              Positioned(
                left: 274.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget5(),
              ),
              Positioned(
                left: 274.0,
                top: 622.0,
                right: null,
                bottom: null,
                width: 90.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget6(),
              ),
              Positioned(
                left: 273.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 14.0,
                child: GeneratedSelengkapnyaWidget7(),
              ),
              Positioned(
                left: 12.0,
                top: 294.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 93.0,
                child: GeneratedImage4Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 82.0,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 102.0,
                child: GeneratedImage6Widget(),
              ),
              Positioned(
                left: 12.0,
                top: 535.0,
                right: null,
                bottom: null,
                width: 91.0,
                height: 83.0,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 289.0,
                top: 677.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup90Widget1(),
              ),
              Positioned(
                left: 295.0,
                top: 684.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcbaselineplusWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 78.0,
                child: GeneratedRectangle58Widget1(),
              ),
              Positioned(
                left: 5.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 311.0,
                height: 94.0,
                child: GeneratedFrame79Widget1(),
              ),
              Positioned(
                left: 313.0,
                top: 64.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 36.0,
                child: GeneratedGroup91Widget1(),
              )
            ]),
      ),
    ));
  }
}
