import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedLine6Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedGroup85Widget7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedKerupuke1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedGroup86Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedKrupuknot1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedGroup84Widget7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedKrupukl1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedKrupukm1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedGroup87Widget7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedGroup83Widget7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedLine2Widget7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedGroup88Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget15/generated/GeneratedLine3Widget7.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget15 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget7(),
              ),
              Positioned(
                left: 135.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 27.0,
                child: GeneratedGroup87Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget7(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 22.0,
                child: GeneratedGroup86Widget5(),
              ),
              Positioned(
                left: 18.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget7(),
              ),
              Positioned(
                left: 0.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget6(),
              ),
              Positioned(
                left: 14.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 126.0,
                child: GeneratedKrupukm1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 497.0,
                right: null,
                bottom: null,
                width: 228.0,
                height: 118.0,
                child: GeneratedKerupuke1Widget(),
              ),
              Positioned(
                left: 20.99287223815918,
                top: 779.7161865234375,
                right: null,
                bottom: null,
                width: 107.7161636352539,
                height: 228.00730895996094,
                child: GeneratedKrupukl1Widget(),
              ),
              Positioned(
                left: 14.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 141.0,
                child: GeneratedKrupuknot1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup88Widget3(),
              )
            ]),
      ),
    ));
  }
}
