import 'package:flutter/material.dart';

/* Text Open 18.00 - Closes 23.00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpen1800Closes2300Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Open 18.00 - Closes 23.00''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
