import 'package:flutter/material.dart';

/* Text Jl. Lawanggada No.23, Pulasaren, Kec. Pekalipan, Kota Cirebon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJlLawanggadaNo23PulasarenKecPekalipanKotaCirebonWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Jl. Lawanggada No.23, Pulasaren, Kec. Pekalipan, Kota Cirebon''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
