import 'package:flutter/material.dart';

/* Text Blok Kaliandul RT.006/RW.003, Setu Kulon, Kec. Weru, Kab. Cirebon
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBlokKaliandulRT006RW003SetuKulonKecWeruKabCirebonWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Blok Kaliandul RT.006/RW.003, Setu Kulon, Kec. Weru, Kab. Cirebon''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
