import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedLine3Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedGgBieLiongNo22PekalipanKecPekalipanKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedNasiLengkoIbuHjSukinahWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedGroup85Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedLine2Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedJlPagonganNo15BPekalanganKecKejaksanKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedOpen0600Closes1600Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedGroup83Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedLine6Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedGroup84Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedOpen0900Closes2200Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedGroup87Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedOpen0600Closes2200Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedGgAlasDemang1No1PekalanganKecPekalipanKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedJlBahagiaPanjunanKecLemahwungkukKotaCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/Generated36147945_409398012896798_2485115154602131456_n300x3001W.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget12/generated/GeneratedOpen0600Closes1600Widget1.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 25.0,
                right: null,
                bottom: null,
                width: 255.0,
                height: 36.0,
                child: GeneratedGroup87Widget4(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget4(),
              ),
              Positioned(
                left: 18.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget4(),
              ),
              Positioned(
                left: 15.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 217.0,
                height: 28.0,
                child: GeneratedNasiLengkoIbuHjSukinahWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget4(),
              ),
              Positioned(
                left: 0.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget3(),
              ),
              Positioned(
                left: 18.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0600Closes2200Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 300.0,
                height: 16.0,
                child:
                    GeneratedJlPagonganNo15BPekalanganKecKejaksanKotaCirebonWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 453.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0900Closes2200Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 439.0,
                right: null,
                bottom: null,
                width: 279.0,
                height: 16.0,
                child:
                    GeneratedJlBahagiaPanjunanKecLemahwungkukKotaCirebonWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0600Closes1600Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 620.0,
                right: null,
                bottom: null,
                width: 326.0,
                height: 16.0,
                child:
                    GeneratedGgAlasDemang1No1PekalanganKecPekalipanKotaCirebonWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 799.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0600Closes1600Widget1(),
              ),
              Positioned(
                left: 15.0,
                top: 785.0,
                right: null,
                bottom: null,
                width: 295.0,
                height: 16.0,
                child:
                    GeneratedGgBieLiongNo22PekalipanKecPekalipanKotaCirebonWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 139.0,
                child:
                    Generated36147945_409398012896798_2485115154602131456_n300x3001W(),
              )
            ]),
      ),
    ));
  }
}
