import 'package:flutter/material.dart';

/* Rectangle nasi-lengko-h-nur 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNasilengkohnur1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 234.0,
      height: 108.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(15.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(15.0),
        child: Image.asset(
          "assets/images/d026da8500bf511bbe4ef977df54f0cb846dae32.png",
          color: null,
          fit: BoxFit.cover,
          width: 234.0,
          height: 108.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
