import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedSelengkapnyaWidget17.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedKebiasaandariparapenjualnyayangmenaruhairgulamerahdalam1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedSampul166216636476041Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedGroup80Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedIcbaselineplusWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedGroup91Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle57Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle56Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedSelengkapnyaWidget18.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedSelengkapnyaWidget19.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedNasijamblangberupanasiyangdibungkusdengandaunjatidandil1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle62Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedEips7xuyao2hvd779945a94fa2a8b20445c2e7e4ba0a19_600x40011.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedEmpalGentongmerupakanmakananyangberasaldariTimurTengahy1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedMaterialsymbolsnavigatenextWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedGroup89Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedSelengkapnyaWidget16.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRekomendasiKulinerKhasCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedGroup81Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedGroup92Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle9Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle54Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle55Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle10Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedGroup90Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro144widget/generated/GeneratedRectangle53Widget.dart';

/* Frame MacBook Pro 14" - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro144Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 982.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 1512.0,
                              height: 98.0,
                              child: GeneratedRectangle53Widget(),
                            ),
                            Positioned(
                              left: 1267.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 54.0,
                              child: GeneratedGroup90Widget2(),
                            ),
                            Positioned(
                              left: 501.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 511.0,
                              height: 51.0,
                              child:
                                  GeneratedRekomendasiKulinerKhasCirebonWidget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle54Widget(),
                            ),
                            Positioned(
                              left: 558.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle10Widget2(),
                            ),
                            Positioned(
                              left: 568.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget16(),
                            ),
                            Positioned(
                              left: 789.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle55Widget(),
                            ),
                            Positioned(
                              left: 1333.0,
                              top: 456.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle62Widget(),
                            ),
                            Positioned(
                              left: 1343.0,
                              top: 466.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget17(),
                            ),
                            Positioned(
                              left: 815.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 58.0,
                              child: GeneratedGroup81Widget2(),
                            ),
                            Positioned(
                              left: 1002.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 471.0,
                              height: 107.0,
                              child:
                                  GeneratedNasijamblangberupanasiyangdibungkusdengandaunjatidandil1(),
                            ),
                            Positioned(
                              left: 806.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 155.0,
                              child:
                                  GeneratedEips7xuyao2hvd779945a94fa2a8b20445c2e7e4ba0a19_600x40011(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 155.0,
                              child: GeneratedRectangle9Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 155.0,
                              child: GeneratedRectangle56Widget(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 50.0,
                              child: GeneratedGroup80Widget2(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 482.0,
                              height: 130.0,
                              child:
                                  GeneratedEmpalGentongmerupakanmakananyangberasaldariTimurTengahy1(),
                            ),
                            Positioned(
                              left: 789.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle60Widget(),
                            ),
                            Positioned(
                              left: 1333.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle63Widget(),
                            ),
                            Positioned(
                              left: 1343.0,
                              top: 795.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget18(),
                            ),
                            Positioned(
                              left: 1002.0,
                              top: 630.0,
                              right: null,
                              bottom: null,
                              width: 495.0,
                              height: 111.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones1(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones2(),
                            ),
                            Positioned(
                              left: 806.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 50.0,
                              child: GeneratedGroup92Widget(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones3(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle57Widget(),
                            ),
                            Positioned(
                              left: 558.0,
                              top: 775.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle61Widget(),
                            ),
                            Positioned(
                              left: 568.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget19(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 158.0,
                              child: GeneratedSampul166216636476041Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 50.0,
                              child: GeneratedGroup91Widget2(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 630.0,
                              right: null,
                              bottom: null,
                              width: 482.0,
                              height: 130.0,
                              child:
                                  GeneratedKebiasaandariparapenjualnyayangmenaruhairgulamerahdalam1(),
                            ),
                            Positioned(
                              left: 723.0,
                              top: 877.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 69.0,
                              child: GeneratedGroup89Widget1(),
                            ),
                            Positioned(
                              left: 734.0,
                              top: 887.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 46.0,
                              child: GeneratedIcbaselineplusWidget2(),
                            ),
                            Positioned(
                              left: 1404.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 71.0,
                              child:
                                  GeneratedMaterialsymbolsnavigatenextWidget(),
                            ),
                            Positioned(
                              left: 806.0,
                              top: 638.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 132.0,
                              child: GeneratedImage2Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
