import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedGroup85Widget8.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedGroup86Widget6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedEmpalgentongmangdarmakulinercirebonlegendaris31Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedJlIrHJuandaNo84DawuanKecTengahTaniKabCirebonWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedOpen0700Closes2100Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedImg202012161017265fe80b3ad541df5761337ef21Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedGroup80Widget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedJlTuparevNo43BSutawinangunKecKedawungKabCirebonWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedRectangle54Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedH4Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedOpen0800Closes2200Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedEmpalGentongWidget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedJlSlametRiadiNo15KesendenKrucukKotaCirebonWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedGroup84Widget8.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedRectangle60Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedGroup77Widget5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedOpen0900Closes2100Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedJlPDiponegoroNo23KesendenKecKejaksanKotaCirebonWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/Generated033611100_1546880129empalgentonghjdiansedapnikmatkuline1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones7.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedRectangle57Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedRectangle53Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedRectangle55Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedOpen0930Closes2130Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro146widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones8.dart';

/* Frame MacBook Pro 14" - 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro146Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 982.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 1512.0,
                              height: 98.0,
                              child: GeneratedRectangle53Widget2(),
                            ),
                            Positioned(
                              left: 643.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 227.0,
                              height: 51.0,
                              child: GeneratedEmpalGentongWidget4(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle54Widget2(),
                            ),
                            Positioned(
                              left: 789.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle55Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 534.0,
                              height: 50.0,
                              child: GeneratedGroup80Widget4(),
                            ),
                            Positioned(
                              left: 789.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle60Widget2(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones7(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones8(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle57Widget2(),
                            ),
                            Positioned(
                              left: 431.0,
                              top: 317.0,
                              right: null,
                              bottom: null,
                              width: 313.0,
                              height: 48.0,
                              child:
                                  GeneratedJlTuparevNo43BSutawinangunKecKedawungKabCirebonWidget2(),
                            ),
                            Positioned(
                              left: 429.0,
                              top: 394.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 22.0,
                              child: GeneratedOpen0900Closes2100Widget3(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 550.0,
                              right: null,
                              bottom: null,
                              width: 490.0,
                              height: 27.0,
                              child: GeneratedGroup84Widget8(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 604.0,
                              right: null,
                              bottom: null,
                              width: 377.0,
                              height: 218.0,
                              child:
                                  GeneratedEmpalgentongmangdarmakulinercirebonlegendaris31Widget1(),
                            ),
                            Positioned(
                              left: 421.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 356.0,
                              height: 65.0,
                              child:
                                  GeneratedJlPDiponegoroNo23KesendenKecKejaksanKotaCirebonWidget2(),
                            ),
                            Positioned(
                              left: 421.0,
                              top: 729.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 22.0,
                              child: GeneratedOpen0700Closes2100Widget3(),
                            ),
                            Positioned(
                              left: 818.0,
                              top: 286.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 195.0,
                              child:
                                  GeneratedImg202012161017265fe80b3ad541df5761337ef21Widget1(),
                            ),
                            Positioned(
                              left: 818.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 458.0,
                              height: 27.0,
                              child: GeneratedGroup85Widget8(),
                            ),
                            Positioned(
                              left: 1216.0,
                              top: 409.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 22.0,
                              child: GeneratedOpen0930Closes2130Widget1(),
                            ),
                            Positioned(
                              left: 1211.0,
                              top: 308.0,
                              right: null,
                              bottom: null,
                              width: 291.0,
                              height: 53.0,
                              child:
                                  GeneratedJlSlametRiadiNo15KesendenKrucukKotaCirebonWidget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 116.0,
                              right: null,
                              bottom: null,
                              width: 63.0,
                              height: 60.0,
                              child: GeneratedGroup77Widget5(),
                            ),
                            Positioned(
                              left: 810.0,
                              top: 603.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 218.0,
                              child:
                                  Generated033611100_1546880129empalgentonghjdiansedapnikmatkuline1(),
                            ),
                            Positioned(
                              left: 811.0,
                              top: 548.0,
                              right: null,
                              bottom: null,
                              width: 397.0,
                              height: 22.0,
                              child: GeneratedGroup86Widget6(),
                            ),
                            Positioned(
                              left: 1192.0,
                              top: 618.0,
                              right: null,
                              bottom: null,
                              width: 304.0,
                              height: 62.0,
                              child:
                                  GeneratedJlIrHJuandaNo84DawuanKecTengahTaniKabCirebonWidget1(),
                            ),
                            Positioned(
                              left: 35.0,
                              top: 292.0,
                              right: null,
                              bottom: null,
                              width: 376.0,
                              height: 200.0,
                              child: GeneratedH4Widget2(),
                            ),
                            Positioned(
                              left: 1194.0,
                              top: 709.0,
                              right: null,
                              bottom: null,
                              width: 249.0,
                              height: 22.0,
                              child: GeneratedOpen0800Closes2200Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
