import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedRectangle46Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedKulinerTopCirebon2Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedRectangle52Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedLogInButtonWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedBieyefillWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedRectangle51Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedNamaWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedPasswordWidget4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedSelamatDatangdiRekomendasiKulinerCirebonWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedEmailWidget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedSignUpWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedLogInButtonWidget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro142widget/generated/GeneratedHELLOWidget1.dart';

/* Frame MacBook Pro 14" - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro142Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 985.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 912.0,
                              height: 985.0,
                              child: GeneratedRectangle1Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.09126984126984126;

                                final double height =
                                    constraints.maxHeight * 0.07230142566191446;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.12118126272912423,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSignUpWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.015873015873015872;

                                final double height = constraints.maxHeight *
                                    0.023421588594704685;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8763227513227513,
                                      y: constraints.maxHeight *
                                          0.7606924643584522,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBieyefillWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04365079365079365;

                                final double height = constraints.maxHeight *
                                    0.034623217922606926;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.3513238289205703,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedNamaWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.07605820105820106;

                                final double height = constraints.maxHeight *
                                    0.034623217922606926;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.5183299389002036,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedEmailWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.3723544973544973;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        563.0;

                                double percentHeight = 0.07739307535641547;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        76.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5376984126984127,
                                      translateY: constraints.maxHeight *
                                          0.39613034623217924,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedRectangle46Widget1())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.3723544973544973;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        563.0;

                                double percentHeight = 0.07739307535641547;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        76.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5376984126984127,
                                      translateY: constraints.maxHeight *
                                          0.5631364562118126,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedRectangle51Widget1())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.07605820105820106;

                                final double height = constraints.maxHeight *
                                    0.034623217922606926;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.6894093686354379,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPasswordWidget4(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.3723544973544973;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        563.0;

                                double percentHeight = 0.07739307535641547;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        76.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5376984126984127,
                                      translateY: constraints.maxHeight *
                                          0.7342158859470469,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedRectangle52Widget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.3723544973544973;

                                final double height =
                                    constraints.maxHeight * 0.07739307535641547;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.8818737270875764,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedLogInButtonWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.10648148148148148;

                                final double height =
                                    constraints.maxHeight * 0.07026476578411406;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.1474867724867725,
                                      y: constraints.maxHeight *
                                          0.7627291242362525,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedLogInButtonWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 255.0,
                              top: 117.0,
                              right: 1170.0,
                              bottom: null,
                              width: null,
                              height: 59.0,
                              child: GeneratedHELLOWidget1(),
                            ),
                            Positioned(
                              left: 63.0,
                              top: 203.0,
                              right: 967.0,
                              bottom: null,
                              width: null,
                              height: 95.0,
                              child:
                                  GeneratedSelamatDatangdiRekomendasiKulinerCirebonWidget2(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 351.0,
                              child: GeneratedKulinerTopCirebon2Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
