import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedLine2Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedJlSunanGnJatiJatimertaKecGunungjatiKabupatenCirebonWidg.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedMieclokpanjunan1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedGroup88Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedGroup88Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedGroup87Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedOpen1000Closes2130Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedGroup83Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedGroup84Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedJt1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedLokasi_mie_koclok_mas_edi1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedMieKoclok1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget9/generated/GeneratedGroup85Widget1.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 17.0,
                top: 80.0,
                right: null,
                bottom: null,
                width: 257.0,
                height: 17.0,
                child: GeneratedGroup83Widget1(),
              ),
              Positioned(
                left: 152.0,
                top: 33.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 27.0,
                child: GeneratedGroup87Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 480.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget1(),
              ),
              Positioned(
                left: 17.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup88Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 144.0,
                child: GeneratedMieclokpanjunan1Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 311.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 126.0,
                child: GeneratedMieKoclok1Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 119.0,
                child: GeneratedLokasi_mie_koclok_mas_edi1Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 675.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 107.0,
                child: GeneratedJt1Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 786.0,
                right: null,
                bottom: null,
                width: 312.0,
                height: 16.0,
                child:
                    GeneratedJlSunanGnJatiJatimertaKecGunungjatiKabupatenCirebonWidg(),
              ),
              Positioned(
                left: 17.0,
                top: 798.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen1000Closes2130Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup88Widget1(),
              )
            ]),
      ),
    ));
  }
}
