import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedJlSyekhDatulKahfiNo50WeruLorKecPleredKabupatenCirebonWi.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedGroup85Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedLine3Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedGroup83Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedJamblangh1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedOpen0500Closes0000Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedOpen0600Closes2100Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedGroup88Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedGroup84Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedNasijamblangphinemocom1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedImage7Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedLine2Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedGroup86Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedNasiJamblangMangDul1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget10/generated/GeneratedGroup87Widget2.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget2(),
              ),
              Positioned(
                left: 122.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 27.0,
                child: GeneratedGroup87Widget2(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 22.0,
                child: GeneratedGroup86Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget1(),
              ),
              Positioned(
                left: 18.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 134.0,
                child: GeneratedImage7Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 137.0,
                child: GeneratedNasiJamblangMangDul1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0500Closes0000Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 128.0,
                child: GeneratedJamblangh1Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 673.0,
                right: null,
                bottom: null,
                width: 236.0,
                height: 111.0,
                child: GeneratedNasijamblangphinemocom1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 799.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0600Closes2100Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 786.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 16.0,
                child:
                    GeneratedJlSyekhDatulKahfiNo50WeruLorKecPleredKabupatenCirebonWi(),
              ),
              Positioned(
                left: 18.0,
                top: 26.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup88Widget2(),
              )
            ]),
      ),
    ));
  }
}
