import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedRectangle46Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedSelamatDatangdiRekomendasiKulinerCirebonWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedKulinerTopCirebon1Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedPasswordWidget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedHELLOWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedPutrijelbungagmailcomWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedLogInButtonWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedEmailWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedLogInButtonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedBieyefillWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedPasswordWidget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedDonthaveanaccountWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedSignUpWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedLogInWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro141widget/generated/GeneratedIforgotmypasswordWidget.dart';

/* Frame MacBook Pro 14" - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro141Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 985.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 600.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 912.0,
                              height: 985.0,
                              child: GeneratedRectangle1Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.09126984126984126;

                                final double height =
                                    constraints.maxHeight * 0.07230142566191446;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.12118126272912423,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedLogInWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.12103174603174603;

                                final double height = constraints.maxHeight *
                                    0.026476578411405296;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.7903439153439153,
                                      y: constraints.maxHeight *
                                          0.659877800407332,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedIforgotmypasswordWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.1746031746031746;

                                final double height = constraints.maxHeight *
                                    0.029531568228105907;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.6507936507936508,
                                      y: constraints.maxHeight *
                                          0.8615071283095723,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedDonthaveanaccountWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.051587301587301584;

                                final double height = constraints.maxHeight *
                                    0.029531568228105907;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.7738095238095238,
                                      y: constraints.maxHeight *
                                          0.860488798370672,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedSignUpWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.015873015873015872;

                                final double height = constraints.maxHeight *
                                    0.023421588594704685;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.8611111111111112,
                                      y: constraints.maxHeight *
                                          0.5896130346232179,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBieyefillWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.08301876713989903;

                                final double height = constraints.maxHeight *
                                    0.010504019478916394;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5541692259450438,
                                      y: constraints.maxHeight *
                                          0.5965221894491471,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPasswordWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.17261904761904762;

                                final double height = constraints.maxHeight *
                                    0.034623217922606926;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5542328042328042,
                                      y: constraints.maxHeight *
                                          0.4195519348268839,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child:
                                            GeneratedPutrijelbungagmailcomWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.04365079365079365;

                                final double height = constraints.maxHeight *
                                    0.034623217922606926;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.3513238289205703,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedEmailWidget2(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.07605820105820106;

                                final double height = constraints.maxHeight *
                                    0.034623217922606926;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.5183299389002036,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedPasswordWidget3(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.3723544973544973;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        563.0;

                                double percentHeight = 0.07739307535641547;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        76.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5376984126984127,
                                      translateY: constraints.maxHeight *
                                          0.39613034623217924,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedRectangle46Widget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                double percentWidth = 0.3723544973544973;
                                double scaleX =
                                    (constraints.maxWidth * percentWidth) /
                                        563.0;

                                double percentHeight = 0.07739307535641547;
                                double scaleY =
                                    (constraints.maxHeight * percentHeight) /
                                        76.0;

                                return Stack(children: [
                                  TransformHelper.translateAndScale(
                                      translateX: constraints.maxWidth *
                                          0.5376984126984127,
                                      translateY: constraints.maxHeight *
                                          0.5631364562118126,
                                      translateZ: 0,
                                      scaleX: scaleX,
                                      scaleY: scaleY,
                                      scaleZ: 1,
                                      child: GeneratedRectangle51Widget())
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.3723544973544973;

                                final double height =
                                    constraints.maxHeight * 0.07739307535641547;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.5376984126984127,
                                      y: constraints.maxHeight *
                                          0.7556008146639511,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedLogInButtonWidget(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.10648148148148148;

                                final double height =
                                    constraints.maxHeight * 0.07026476578411406;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.14153439153439154,
                                      y: constraints.maxHeight *
                                          0.7627291242362525,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedLogInButtonWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 117.0,
                              right: 1175.0,
                              bottom: null,
                              width: null,
                              height: 59.0,
                              child: GeneratedHELLOWidget(),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 203.0,
                              right: 976.0,
                              bottom: null,
                              width: null,
                              height: 95.0,
                              child:
                                  GeneratedSelamatDatangdiRekomendasiKulinerCirebonWidget1(),
                            ),
                            Positioned(
                              left: 120.0,
                              top: 321.0,
                              right: null,
                              bottom: null,
                              width: 337.0,
                              height: 351.0,
                              child: GeneratedKulinerTopCirebon1Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
