import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedGroup87Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedGroup84Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedGroup85Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedKulinerkotajakarta_10_8_2018_14_34_24_2541024x10241Widg.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedGroup86Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedReseptahugejrotkhascirebon1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedGroup83Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedGroup77Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedOpen1100Closes2000Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedJrot1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget8/generated/GeneratedTahuGejrotJajanankhasWongCirebon1Widget.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 17.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget(),
              ),
              Positioned(
                left: 137.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 27.0,
                child: GeneratedGroup87Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 164.0,
                child: GeneratedGroup86Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 96.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 147.0,
                child: GeneratedTahuGejrotJajanankhasWongCirebon1Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 304.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 124.0,
                child:
                    GeneratedKulinerkotajakarta_10_8_2018_14_34_24_2541024x10241Widg(),
              ),
              Positioned(
                left: 22.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen1100Closes2000Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 221.0,
                height: 117.0,
                child: GeneratedReseptahugejrotkhascirebon1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 671.0,
                right: null,
                bottom: null,
                width: 223.0,
                height: 109.0,
                child: GeneratedJrot1Widget(),
              ),
              Positioned(
                left: 20.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup77Widget(),
              )
            ]),
      ),
    ));
  }
}
