import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedVector2Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedLupapasswordWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedAccount_circleWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedSelamatDatangdiRekomendasiKulinerCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedVector1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedBelumPunyaAkunDaftarWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedKulinerTopCirebon1Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedHelloWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedLockWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedandroidsmall1widget/generated/GeneratedEmailWidget.dart';

/* Frame Android Small - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidSmall1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 115.0,
                top: null,
                right: 96.0,
                bottom: 44.0,
                width: null,
                height: 16.0,
                child: GeneratedBelumPunyaAkunDaftarWidget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: 103.0,
                bottom: 84.0,
                width: 137.0,
                height: 40.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 460.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 72.0;
                  final double scaleX = width <= 0 ? 0 : (width / 288.0);

                  final Widget child = GeneratedVector1Widget();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 36.0 * scaleX, 460.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 35.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAccount_circleWidget(),
              ),
              Positioned(
                left: 35.0,
                top: 432.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedLockWidget(),
              ),
              Positioned(
                left: 145.0,
                top: 56.0,
                right: 143.0,
                bottom: null,
                width: null,
                height: 28.0,
                child: GeneratedHelloWidget(),
              ),
              Positioned(
                left: 53.0,
                top: 94.0,
                right: 29.0,
                bottom: null,
                width: null,
                height: 44.0,
                child:
                    GeneratedSelamatDatangdiRekomendasiKulinerCirebonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 382.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 0.0,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth - 72.0;
                  final double scaleX = width <= 0 ? 0 : (width / 288.0);

                  final Widget child = GeneratedVector2Widget();
                  return Stack(children: [
                    Transform(
                      transform: Matrix4(scaleX, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
                          0, 36.0 * scaleX, 382.0, 0, 1),
                      alignment: Alignment.topLeft,
                      child: SizedBox.expand(child: child),
                    )
                  ]);
                }),
              ),
              Positioned(
                left: 67.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 33.0,
                height: 21.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 233.0,
                top: 475.0,
                right: null,
                bottom: null,
                width: 85.0,
                height: 18.0,
                child: GeneratedLupapasswordWidget(),
              ),
              Positioned(
                left: 67.0,
                top: 433.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 21.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 91.0,
                top: 160.0,
                right: null,
                bottom: null,
                width: 194.0,
                height: 159.0,
                child: GeneratedKulinerTopCirebon1Widget(),
              )
            ]),
      ),
    ));
  }
}
