import 'package:flutter/material.dart';

/* Text Jl. Pekalipan No.99, Pekalipan, Kec. Pekalipan, Kota Cirebon Open 18.00 - Closes 23.30
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedJlPekalipanNo99PekalipanKecPekalipanKotaCirebonOpen1800
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Jl. Pekalipan No.99, Pekalipan, Kec. Pekalipan, Kota Cirebon
Open 18.00 - Closes 23.30''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
