import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRekomendasiKulinerKhasCirebonWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedSelengkapnyaWidget23.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedSelengkapnyaWidget21.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedSampul166216636476041Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup81Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle57Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup93Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle60Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup92Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle10Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle61Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle63Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones4.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle53Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup89Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle54Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle55Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedIcbaselineplusWidget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle76Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedNasijamblangberupanasiyangdibungkusdengandaunjatidandil2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedMaterialsymbolsnavigatenextWidget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedImage2Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedSelengkapnyaWidget20.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup80Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedEmpalGentongmerupakanmakananyangberasaldariTimurTengahy2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones5.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle62Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedSelengkapnyaWidget22.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedBelumWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones6.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedEips7xuyao2hvd779945a94fa2a8b20445c2e7e4ba0a19_600x40012.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedRectangle56Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedSelesaiWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup90Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedGroup91Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedmacbookpro1414widget/generated/GeneratedKebiasaandariparapenjualnyayangmenaruhairgulamerahdalam2.dart';

/* Frame MacBook Pro 14" - 14
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMacBookPro1414Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(20.0),
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 982.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1512.0,
                      height: 982.0,
                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(20.0),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.circular(20.0),
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 97.0,
                              right: null,
                              bottom: null,
                              width: 1512.0,
                              height: 98.0,
                              child: GeneratedRectangle53Widget1(),
                            ),
                            Positioned(
                              left: 1267.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 94.0,
                              height: 54.0,
                              child: GeneratedGroup90Widget3(),
                            ),
                            Positioned(
                              left: 501.0,
                              top: 121.0,
                              right: null,
                              bottom: null,
                              width: 511.0,
                              height: 51.0,
                              child:
                                  GeneratedRekomendasiKulinerKhasCirebonWidget1(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle54Widget1(),
                            ),
                            Positioned(
                              left: 558.0,
                              top: 463.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle10Widget3(),
                            ),
                            Positioned(
                              left: 568.0,
                              top: 473.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget20(),
                            ),
                            Positioned(
                              left: 789.0,
                              top: 212.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle55Widget1(),
                            ),
                            Positioned(
                              left: 1333.0,
                              top: 456.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle62Widget1(),
                            ),
                            Positioned(
                              left: 1343.0,
                              top: 466.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget21(),
                            ),
                            Positioned(
                              left: 815.0,
                              top: 234.0,
                              right: null,
                              bottom: null,
                              width: 267.0,
                              height: 58.0,
                              child: GeneratedGroup81Widget3(),
                            ),
                            Positioned(
                              left: 1002.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 471.0,
                              height: 107.0,
                              child:
                                  GeneratedNasijamblangberupanasiyangdibungkusdengandaunjatidandil2(),
                            ),
                            Positioned(
                              left: 806.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 155.0,
                              child:
                                  GeneratedEips7xuyao2hvd779945a94fa2a8b20445c2e7e4ba0a19_600x40012(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 155.0,
                              child: GeneratedRectangle9Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 305.0,
                              right: null,
                              bottom: null,
                              width: 158.0,
                              height: 155.0,
                              child: GeneratedRectangle56Widget1(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 225.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 50.0,
                              child: GeneratedGroup80Widget3(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 306.0,
                              right: null,
                              bottom: null,
                              width: 482.0,
                              height: 130.0,
                              child:
                                  GeneratedEmpalGentongmerupakanmakananyangberasaldariTimurTengahy2(),
                            ),
                            Positioned(
                              left: 789.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle60Widget1(),
                            ),
                            Positioned(
                              left: 1333.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle63Widget1(),
                            ),
                            Positioned(
                              left: 1343.0,
                              top: 795.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget22(),
                            ),
                            Positioned(
                              left: 1002.0,
                              top: 630.0,
                              right: null,
                              bottom: null,
                              width: 495.0,
                              height: 111.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones4(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones5(),
                            ),
                            Positioned(
                              left: 806.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 50.0,
                              child: GeneratedGroup92Widget1(),
                            ),
                            Positioned(
                              left: 113.0,
                              top: 563.0,
                              right: null,
                              bottom: null,
                              width: 263.0,
                              height: 76.0,
                              child:
                                  GeneratedHidanganmiyangberasaldariwilayahCirebonJawaBaratIndones6(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 539.0,
                              right: null,
                              bottom: null,
                              width: 706.0,
                              height: 296.0,
                              child: GeneratedRectangle57Widget1(),
                            ),
                            Positioned(
                              left: 558.0,
                              top: 775.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 34.0,
                              child: GeneratedRectangle61Widget1(),
                            ),
                            Positioned(
                              left: 568.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 22.0,
                              child: GeneratedSelengkapnyaWidget23(),
                            ),
                            Positioned(
                              left: 39.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 148.0,
                              height: 158.0,
                              child: GeneratedSampul166216636476041Widget2(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 295.0,
                              height: 50.0,
                              child: GeneratedGroup91Widget3(),
                            ),
                            Positioned(
                              left: 208.0,
                              top: 630.0,
                              right: null,
                              bottom: null,
                              width: 482.0,
                              height: 130.0,
                              child:
                                  GeneratedKebiasaandariparapenjualnyayangmenaruhairgulamerahdalam2(),
                            ),
                            Positioned(
                              left: 723.0,
                              top: 877.0,
                              right: null,
                              bottom: null,
                              width: 68.0,
                              height: 69.0,
                              child: GeneratedGroup89Widget2(),
                            ),
                            Positioned(
                              left: 734.0,
                              top: 887.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 46.0,
                              child: GeneratedIcbaselineplusWidget3(),
                            ),
                            Positioned(
                              left: 1404.0,
                              top: 112.0,
                              right: null,
                              bottom: null,
                              width: 105.0,
                              height: 71.0,
                              child:
                                  GeneratedMaterialsymbolsnavigatenextWidget1(),
                            ),
                            Positioned(
                              left: 806.0,
                              top: 638.0,
                              right: null,
                              bottom: null,
                              width: 180.0,
                              height: 132.0,
                              child: GeneratedImage2Widget2(),
                            ),
                            Positioned(
                              left: 418.0,
                              top: 311.0,
                              right: null,
                              bottom: null,
                              width: 925.0,
                              height: 403.0,
                              child: GeneratedRectangle76Widget(),
                            ),
                            Positioned(
                              left: 558.0,
                              top: 422.0,
                              right: null,
                              bottom: null,
                              width: 646.0,
                              height: 102.0,
                              child: GeneratedGroup93Widget(),
                            ),
                            Positioned(
                              left: 510.0,
                              top: 622.0,
                              right: null,
                              bottom: null,
                              width: 116.0,
                              height: 35.0,
                              child: GeneratedSelesaiWidget(),
                            ),
                            Positioned(
                              left: 1122.0,
                              top: 628.0,
                              right: null,
                              bottom: null,
                              width: 109.0,
                              height: 35.0,
                              child: GeneratedBelumWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
