import 'package:flutter/material.dart';

/* Text Open 15.30 - Closes 22:00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOpen1530Closes2200Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Open 15.30 - Closes 22:00''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.4,
        fontSize: 10.0,
        fontFamily: 'Biryani',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
