import 'package:flutter/material.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedGroup85Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedLine3Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedOpen0800Closes2200Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedGroup77Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedGroup83Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedH4Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedImg202012161017265fe80b3ad541df5761337ef21Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedJlIrHJuandaNo84DawuanKecTengahTaniKabCirebonWidget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedGroup87Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedLine2Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedOpen0700Closes2100Widget1.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedEmpalgentongmangdarmakulinercirebonlegendaris31Widget.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedGroup86Widget2.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedGroup84Widget3.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/Generated033611100_1546880129empalgentonghjdiansedapnikmatkuline.dart';
import 'package:flutterapp/kuliner_20cirebonapp/generatedselengkapnyawidget11/generated/GeneratedLine6Widget2.dart';

/* Frame Selengkapnya
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSelengkapnyaWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 245, 242, 242),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 226.0,
                height: 17.0,
                child: GeneratedGroup83Widget3(),
              ),
              Positioned(
                left: 122.0,
                top: 32.0,
                right: null,
                bottom: null,
                width: 131.0,
                height: 27.0,
                child: GeneratedGroup87Widget3(),
              ),
              Positioned(
                left: 20.0,
                top: 278.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup84Widget3(),
              ),
              Positioned(
                left: 21.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 291.0,
                height: 22.0,
                child: GeneratedGroup86Widget2(),
              ),
              Positioned(
                left: 18.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 27.0,
                child: GeneratedGroup85Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine2Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine3Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 650.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 1.0,
                child: GeneratedLine6Widget2(),
              ),
              Positioned(
                left: 21.0,
                top: 455.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0700Closes2100Widget1(),
              ),
              Positioned(
                left: 21.0,
                top: 797.0,
                right: null,
                bottom: null,
                width: 126.0,
                height: 16.0,
                child: GeneratedOpen0800Closes2200Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 783.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 16.0,
                child:
                    GeneratedJlIrHJuandaNo84DawuanKecTengahTaniKabCirebonWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 235.0,
                height: 140.0,
                child: GeneratedH4Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 136.0,
                child:
                    GeneratedEmpalgentongmangdarmakulinercirebonlegendaris31Widget(),
              ),
              Positioned(
                left: 21.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 250.0,
                height: 119.0,
                child:
                    GeneratedImg202012161017265fe80b3ad541df5761337ef21Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 673.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 106.0,
                child:
                    Generated033611100_1546880129empalgentonghjdiansedapnikmatkuline(),
              ),
              Positioned(
                left: 18.0,
                top: 24.0,
                right: null,
                bottom: null,
                width: 36.0,
                height: 36.0,
                child: GeneratedGroup77Widget1(),
              )
            ]),
      ),
    ));
  }
}
